name: deepmuonreco-py312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytorch-gpu=2.6.0
  - tensordict=0.7.2
  - einops=0.8.1
  - torchmetrics=1.7.0
  - aim
  - uproot
  - hist
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - ipykernel
